#!/bin/bash
# needs bgscripts >= 1.1-26
. /usr/bgscripts/bgscripts.bashrc --noclear --nodeps

type="";

case "${thisflavor}" in
   redhat|rhel|centos|fedora|korora) type=rpm;;
   debian|ubuntu) type=dpkg;;
   *) type=targz;;
esac

echo " $@ " | grep -qiE -- "rpm|rhel|redhat|centos|fedora|korora" 1>/dev/null 2>&1 && type=rpm
echo " $@ " | grep -qiE -- "debian|ubuntu|deb\s|dpkg" 1>/dev/null 2>&1 && type=dpkg
echo " $@ " | grep -qiE -- "tar|tgz|gz" 1>/dev/null 2>&1 && type=targz


echo "packaging ${type}"
echo " $@ " | grep -qiE -- "debug|\B-d[ 0-9]{0,3}\s" 1>/dev/null 2>&1 && exit

case "${type}" in
   rpm)

########## PACKAGING for rhel/centos/fedora
rpmbuilddir=~/rpmbuild/
package=irfan
version=4.44-1
shortversion=4.44
packagespecfile="${package}-${version}/usr/share/${package}/docs/${package}.spec"
sed -n -e '1,/^\%files$/p;' "${rpmbuilddir}/SOURCES/${packagespecfile}" > "${rpmbuilddir}/SOURCES/${packagespecfile}.swp" #removes files and changelog
cd ${rpmbuilddir}/SOURCES/"${package}-${version}"
find * ! -regex '.*?.swp' ! -regex '>*?DEBIAN.*?' | sed -e 's/^/\//;' -e 's/\(\(.*packaging\|.*README\)\.txt\)/%doc %attr(444, -, -) \1/;' -e 's/\(.*\.ini\)/%config %attr(666, -, -) \1/;' -e 's/\(.*\.sh\)/%attr(755, -, -) \1/;' -e 's/\(.*\.desktop\)/%attr(644, -, -) \1/;' >> ${rpmbuilddir}/SOURCES/"${packagespecfile}.swp"
sed -n -e '/^\%changelog/,$p' "${rpmbuilddir}/SOURCES/${packagespecfile}" >> "${rpmbuilddir}/SOURCES/${packagespecfile}.swp"
mv -f "${rpmbuilddir}/SOURCES/${packagespecfile}.swp" "${rpmbuilddir}/SOURCES/${packagespecfile}"
rm -rf ${rpmbuilddir}/SOURCES/"${package}-${shortversion}"; cp -prf ${rpmbuilddir}/SOURCES/"${package}-${version}" ${rpmbuilddir}/SOURCES/"${package}-${shortversion}"
rm -rf ${rpmbuilddir}/SOURCES/"${package}-${shortversion}"/DEBIAN
cd "${rpmbuilddir}/SOURCES"
rm -rf "${package}.tgz"; tar -zc --exclude='.git' -f "${package}.tgz" "${package}-${shortversion}"
/bin/cp -pf "${rpmbuilddir}/SOURCES/${packagespecfile}" "${rpmbuilddir}/SPECS"
cd "${rpmbuilddir}/RPMS/noarch"
rpmbuild -bb "${rpmbuilddir}/SPECS/${package}.spec"

      ;;
   dpkg)

########## PACKAGING for debian
# You need package dpkg-dev to build packages
package=irfan
version=4.44-1
packagedebfilesdir="${package}-${version}/usr/share/${package}/docs/debian"
cd ~/deb/"${package}-${version}"
find . -type f ! -regex '.*.hg.*' ! -regex '.*?debian-binary.*' ! -regex '.*?DEBIAN.*' ! -regex '.*?.swp' ! -regex '.*\.git.*' -printf '%P ' | xargs md5sum > ~/deb/"${packagedebfilesdir}"/md5sums
rm -rf ~/deb/"${package}-${version}"/DEBIAN/ 2>/dev/null; mkdir -p ~/deb/"${package}-${version}"/DEBIAN/
cp -pf ~/deb/"${packagedebfilesdir}"/* ~/deb/"${package}-${version}"/DEBIAN/
cd ~/deb
rm -rf ~/deb/"${package}-${version}.a"
cp -pR ~/deb/"${package}-${version}" ~/deb/"${package}-${version}.a"
rm -rf ~/deb/"${package}-${version}"/.git
dpkg-deb -b ~/deb/"${package}-${version}"
rm -rf ~/deb/"${package}-${version}"
mv ~/deb/"${package}-${version}.a" ~/deb/"${package}-${version}"

      ;;
   targz)

### PACKAGING in a master.tgz
cd ~/deb 2>/dev/null || cd ~/rpmbuild/SOURCES
package=irfan
version=4.44-1
rm -rf ./"${package}-${version}".master.tgz
tar -zcf ./"${package}-${version}".master.tgz "${package}-${version}"/

      ;;
   unknown)
      echo "error: check $0 for errors on type ${type}." 1>&2
      ;;
esac
